[package]
name = "pentest-notes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
futures = "0.3.30"
ratatui = { version = "0.26.1", features = ["all-widgets", "serde"] }
serde = "1.0.197"
serde_derive = "1.0.197"
tokio = "1.37.0"
tokio-util = "0.7.10"
